### ISSUE TITLE
Mintel reports

### ISSUE THREAD

**Issue by MikeBohan** [MikeBohan/fame-marketing#35]

**Comment by jmarzetti** [comment]
No access to Mintel- but we can access  'Marketline' and 'Business Monitor International' reports. I will start storing the reports in a dropbox folder this morning.

**Comment by jmarzetti** [comment]
I have added 2 separate folders to my dropbox 'Market Reports' and 'Fantasy Gaming'. I have started to collate some relevant report documents in these folders and will add to them as we go.
