### ISSUE TITLE
PR Agency Research

### ISSUE THREAD

**Issue by MikeBohan** [MikeBohan/fame-marketing#54]

**Comment by MikeBohan** [comment]
Make a short list of PR agencies associated with football.

**Comment by jmarzetti** [comment]
https://www.dropbox.com/s/wtgfleiebacig97/PR%20Company%20Startup%20List%20%2805.05.15%29.xlsx?dl=0

**Comment by jmarzetti** [comment]
https://www.dropbox.com/s/3cblxptc1w9np55/PR%20Company%20Startup%20List%20%2812.05.15%29.xlsx?dl=0 updated list
