### ISSUE TITLE
Video Instructions

### ISSUE THREAD

**Issue by MikeBohan** [MikeBohan/fame-marketing#56]

**Comment by MikeBohan** [comment]
Script some tutorial videos for FootballINDEX.

**Comment by jmarzetti** [comment]
https://www.dropbox.com/s/v4avb7wq7wbeaku/Video%20Tutorial%20Script%20Drafts.docx?dl=0

**Comment by jmarzetti** [comment]
https://www.dropbox.com/s/1oukln931kla48g/Instructional%20Video%20Scripts.pptx?dl=0
