### ISSUE TITLE
Video Research

### ISSUE THREAD

**Issue by MikeBohan** [MikeBohan/fame-marketing#58]
Please collate a list of betting instructional videos that do a good job telling the story. Look at spread betting, betfair and other financial instruments like IG Index

**Comment by jmarzetti** [comment]
https://www.dropbox.com/s/v4avb7wq7wbeaku/Video%20Tutorial%20Script%20Drafts.docx?dl=0

**Comment by jmarzetti** [comment]
https://www.youtube.com/watch?v=tIhgCAlP0RU- Sporting Index
https://www.youtube.com/watch?v=B4l4UgPbDY0- Spread-Ex
https://www.youtube.com/watch?v=Rjdt2mqvX-0- Spread-Ex
https://www.youtube.com/watch?v=n5xym1_Gv-g- Paddy Power (tutorial)
http://www.cityindex.co.uk/spread-betting/
http://www.ig.com/uk/spread-betting
https://www.youtube.com/watch?v=jVTUwUc7EN0- The Sports Geek
